# .github/workflows/cd.yml
name: CD Pipeline (Push via SSH)

on:
  workflow_run:
    workflows: ["Continuous Integration & Package"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Blue-Green Deploy to AWS EC2
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: SSH 원격 접속 및 Blue/Green 무중단 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Connected to EC2 via SSH."
            ~/deploy.sh